stages:
  split:
    cmd: python src/split.py
    deps:
    - data/raw/train
    - src/split.py
    params:
    - split.ratio
    outs:
    - data/raw/test
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw
    - src/preprocess.py
    params:
    - preprocess
    outs:
    - data/prepared
  train:
    cmd: python src/train.py
    deps:
    - data
    - src/train.py
    outs:
    - evaluation/report.html:
        cache: false
    - models
    metrics:
    - evaluation/metrics.json:
        cache: false
    plots:
    - evaluation/plots
